sub_filter_once on;
sub_filter_types text/html;
sub_filter 'Getting started' 'BlueHesab (بلوحساب)';
sub_filter 'Setup'           'DataBase (دیتابیس)';
sub_filter 'Plugins'         'CRM (مدیریت ارتباط)';
sub_filter 'Reference'       'BlueHab HR (منابع انسانی)';
sub_filter 'Insiders'        'BlueWire (بلو وایر)';
sub_filter 'Community'       'BlueAPi (بلو ای پی آی)';
sub_filter 'Blog'            'BlueDoc (بلوداک)';
