    location = /docs      { return 301 /stage/; }
    location ^~ /docs/    { return 301 /stage/docs/; }
    location = /blueapi   { return 301 /stage/; }
    location ^~ /blueapi/ { return 301 /stage/docs/; }
