server {
    listen 80;
    server_name docs.bluehesab.ir;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name docs.bluehesab.ir;

    ssl_certificate     /etc/letsencrypt/live/docs.bluehesab.ir/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/docs.bluehesab.ir/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;

    root  /srv/bluedoc/main;
    index index.html;

    # حالا ریشه واقعاً همون هوم‌پیج تو میشه
    location = / {
        try_files /index.html =404;
    }

    location ^~ /assets/ {
        access_log off;
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location ^~ /_blue/ {
        alias /srv/bluedoc/main/_blue/;
        access_log off;
        try_files $uri =404;
        add_header Cache-Control "no-store";
    }

    # داکس ERP
    location = /blueapi { return 302 /blueapi/; }

    location ^~ /blueapi/assets/ {
        alias /srv/bluedoc/main/blueapi/assets/;
        access_log off;
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location ^~ /blueapi/ {
        alias /srv/bluedoc/main/blueapi/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location = /service-worker.js            { return 410; }
    location = /manifest.webmanifest         { return 410; }
    location = /blueapi/service-worker.js    { return 410; }
    location = /blueapi/manifest.webmanifest { return 410; }

    location = /assets/blueapi_help.js {
        alias /srv/bluedoc/main/assets/blueapi_help.js;
        default_type application/javascript;
        add_header Cache-Control "no-store" always;
        access_log off;
    }
}
