upstream frappe-bench-frappe {
    server 127.0.0.1:8000 fail_timeout=0;
}

upstream frappe-bench-socketio {
    server 127.0.0.1:9000 fail_timeout=0;
}

# http -> https
server {
    listen 80;
    server_name baba.bluehesab.ir;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name baba.bluehesab.ir;

    ssl_certificate     /etc/letsencrypt/live/baba.bluehesab.ir/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/baba.bluehesab.ir/privkey.pem;

    # این باید همین باشه
    root /home/frappe/frappe-bench/sites;
    client_max_body_size 50m;

    # ----------------- استاتیک‌های فِرَپی / ERPNext
    location /assets {
        try_files $uri =404;
    }

    # ----------------- فایل‌های آپلود شده‌ی سایتت
    # این فقط همون /files/... رو می‌ده، بس.
    location /files/ {
        alias /home/frappe/frappe-bench/sites/baba.bluehesab.ir/public/files/;
        autoindex off;
    }

    # ----------------- این فایل تک‌تومتیکی که ساختیم
    location = /blueapi_boot.js {
        alias /home/frappe/frappe-bench/sites/baba.bluehesab.ir/public/blueapi_boot.js;
    }

    # ----------------- socket.io
    location /socket.io {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Frappe-Site-Name baba.bluehesab.ir;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://frappe-bench-socketio;
    }

    # ----------------- بقیه‌ی درخواست‌ها برن به فِرَپی
    location / {
        try_files $uri @frappe;
    }

    location @frappe {
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header X-Frappe-Site-Name baba.bluehesab.ir;
        proxy_set_header X-Use-X-Accel-Redirect True;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120;
        proxy_redirect off;
        proxy_pass http://frappe-bench-frappe;
    }
}
